name: crdt_sync
description: A dart-native turnkey solution for painless network synchronization
version: 0.0.3
repository: https://github.com/cachapa/crdt_sync

environment:
  sdk: ^3.0.0

dependencies:
  sql_crdt: ^1.1.1
#    path: ../sql_crdt
  sqlparser: ^0.30.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: any
  test: any

  # Example
  sqlite_crdt: any
#    path: ../sqlite_crdt
  uuid: any
